Repository Qwant/erdapfel, pull requests merged in 2020-12, with the labels that each got.

#961 Fix transparent gradient used as ellipsis on iOS
  src/scss/includes/panels/poi_panel.scss
Labels: bug, easy review

#964 Move autocomplete style to suggest.scss
  src/scss/includes/search_form.scss
  src/scss/includes/suggest.scss
  src/scss/main.scss
Labels: easy review

#965 Improve Search form layout
  src/scss/includes/menu.scss
  src/scss/includes/search_form.scss
  views/index.ejs
Labels: tech

#960 [Tests] Run integration suite on desktop and mobile devices
  package.json
  tests/integration.js
  tests/integration/device.js
  tests/integration/tests/autocomplete.desktop.js
  tests/integration/tests/autocomplete.js
  tests/integration/tests/direction.desktop.js
  tests/integration/tests/direction.js
  tests/integration/tests/direction.mobile.js
  tests/integration/tests/menu.desktop.js
  tests/integration/tests/menu.js
  tests/integration/tests/poi.desktop.js
  tests/integration/tests/poi.js
  tests/integration/tools.js
Labels: PoC, tech
